steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/projet-group-a/mick-worker:latest','./worker/.']
    id: worker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/projet-group-a/mick-vote:latest','./vote/.']
    id: vote
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/projet-group-a/mick-result:latest','./result/.']  
    id: result
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/projet-group-a/mick-redis:latest','./redis/.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/projet-group-a/mick-postgres:latest','./postgresSQL/.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: [worker]
    entrypoint : gcloud
    args : ['run', 'deploy', 'test-flask-hello-ci-cd', '--image', 'gcr.io/projet-group-a/mick-worker:latest', '--region', 'europe-west1', '--allow-unauthenticated']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: [vote]
    entrypoint : gcloud
    args : ['run', 'deploy', 'test-flask-hello-ci-cd', '--image', 'gcr.io/projet-group-a/mick-vote:latest', '--region', 'europe-west1', '--port', '80', '--allow-unauthenticated']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    waitFor: [result]
    entrypoint : gcloud
    args : ['run', 'deploy', 'test-flask-hello-ci-cd', '--image', 'gcr.io/projet-group-a/mick-result:latest', '--region', 'europe-west1', '--port', '4000', '--allow-unauthenticated']


images: [gcr.io/projet-group-a/mick-vote:latest,gcr.io/projet-group-a/mick-worker:latest,gcr.io/projet-group-a/mick-result:latest,gcr.io/projet-group-a/mick-redis:latest,gcr.io/projet-group-a/mick-postgres:latest]